[package]
name = "cards"
version = "0.1.0"
authors = ["Vladislav Supalov <v.supalov@gmail.com>"]
description = "Reusable playing cards library for Rust."
license = "BSD-3-Clause"

[lib]
name = "cards"

[dependencies]
rand = "0.3.7"
