[package]
name = "cards"
version = "1.1.0"
authors = ["Vladislav Supalov <v.supalov@gmail.com>"]
keywords = ["cards", "poker"]
description = "Reusable playing cards library for Rust."
license = "MIT"
readme = "README.md"

[lib]
name = "cards"

[dependencies]
rand = "0.3.8"
