[package]
name = "cards"
version = "0.1.0"
authors = ["Vladislav Supalov <v.supalov@gmail.com>"]
description = "Reusable playing cards library for Rust."

[lib]
name = "cards"

[dependencies]
rand = "0.3.8"
